// Created by iWeb 3.0.4 local-build-20171107

setTransparentGifURL('Media/transparent.gif');function applyEffects()
{var registry=IWCreateEffectRegistry();registry.registerEffects({stroke_2:new IWEmptyStroke(),stroke_0:new IWStrokeParts([{rect:new IWRect(-1,1,2,94),url:'index_files/stroke.png'},{rect:new IWRect(-1,-1,2,2),url:'index_files/stroke_1.png'},{rect:new IWRect(1,-1,1015,2),url:'index_files/stroke_2.png'},{rect:new IWRect(1016,-1,2,2),url:'index_files/stroke_3.png'},{rect:new IWRect(1016,1,2,94),url:'index_files/stroke_4.png'},{rect:new IWRect(1016,95,2,2),url:'index_files/stroke_5.png'},{rect:new IWRect(1,95,1015,2),url:'index_files/stroke_6.png'},{rect:new IWRect(-1,95,2,2),url:'index_files/stroke_7.png'}],new IWSize(1017,96)),stroke_1:new IWStrokeParts([{rect:new IWRect(-1,1,2,21),url:'index_files/stroke_8.png'},{rect:new IWRect(-1,-1,2,2),url:'index_files/stroke_9.png'},{rect:new IWRect(1,-1,1006,2),url:'index_files/stroke_10.png'},{rect:new IWRect(1007,-1,2,2),url:'index_files/stroke_11.png'},{rect:new IWRect(1007,1,2,21),url:'index_files/stroke_12.png'},{rect:new IWRect(1007,22,2,2),url:'index_files/stroke_13.png'},{rect:new IWRect(1,22,1006,2),url:'index_files/stroke_14.png'},{rect:new IWRect(-1,22,2,2),url:'index_files/stroke_15.png'}],new IWSize(1008,23))});registry.applyEffects();}
function hostedOnDM()
{return false;}
function onPageLoad()
{loadMozillaCSS('index_files/indexMoz.css')
adjustLineHeightIfTooBig('id1');adjustFontSizeIfTooBig('id1');adjustLineHeightIfTooBig('id2');adjustFontSizeIfTooBig('id2');adjustLineHeightIfTooBig('id3');adjustFontSizeIfTooBig('id3');adjustLineHeightIfTooBig('id4');adjustFontSizeIfTooBig('id4');adjustLineHeightIfTooBig('id5');adjustFontSizeIfTooBig('id5');adjustLineHeightIfTooBig('id6');adjustFontSizeIfTooBig('id6');adjustLineHeightIfTooBig('id7');adjustFontSizeIfTooBig('id7');fixAllIEPNGs('Media/transparent.gif');applyEffects()}
